font_family      "FiraCode Nerd Font"
font_size        9
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

cursor_sheap     beam

tab_bar_min_tabs 1
tab_bar_edge     bottom
tab_bar_style    powerline
tab_powerline_style slanted
tab_title_template "{title}{' :{}:'.format(num_windows) if num_windows > 1 else ''"

background_opacity 1
background_blur 1
window_padding_width 10
enable_audio_bell no
hide_window_decorations no

copy_on_select   true

background       #0C0C0C
cursor           #f5e0dc
cursor_text_color #1e1e2e

url_color        #f5e0dc

active_tab_foreground #11111b
active_tab_background #cba6f7
inactive_tab_foregound #cdd6f4
inactive_tab_background #1f1f1f

mark1_foreground #1e1e2e
mark1_background #b4befe
mark2_foreground #1e1e2e
mark2_background #cba6f7
mark3_foreground #1e1e2e
mark3_background #74c7ec

# The 16 terminal colors

# black
color0 #100F0F
color8 #6F6E69

# red
color1 #D14D41
color9 #D14D41

# green
color2  #879A39
color10 #879A39

# yellow
color3  #D0A215
color11 #D0A215

# blue
color4  #4385BE
color12 #4385BE

# magenta
color5  #CE5D97
color13 #CE5D97

# cyan
color6  #3AA99F
color14 #3AA99F

# white
color7  #E6E4D9
color15 #E6E4D9


# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
