set -g prefix `
bind ` send-prefix

unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -sg terminal-overrides ",*:RGB"

set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on
set -g escape-time 0
set -g mouse on
set -g repeat-time 1000
set -g history-limit 10000

bind g split-window -h
bind v split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind f resize-pane -Z

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'

# bloatware from catppuccin

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'

set -g @catppuccin_date_time_text " %F %R "
set -g @catppuccin_directory_text " #{b:pane_current_path} "
set -g @catppuccin_status_background "none"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_window_current_background "#313244"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_default_background "#252434"
set -g @catppuccin_window_default_fill "all"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_status_style "none"

set -g status-left ""
set -g status-left-length 100
set -g status-position top
set -g status-right "#{E:@catppuccin_status_session}#{E:@catppuccin_status_host}#{E:@catppuccin_status_directory}#{E:@catppuccin_status_date_time}"
set -g status-right-length 100

set -g window-status-current-format "#[fg=#313244,bg=default]#[fg=#cdd6f4,bg=#313244] #{pane_current_command}#{?window_zoomed_flag, 🔍,} #[fg=#313244,bg=#cba6f7] #I #[fg=#cba6f7,bg=default]"
set -g window-status-current-style "bg=default,fg=#313244"
set -g window-status-format "#[fg=#252434,bg=default]#[fg=#cdd6f4,bg=#252434] #{pane_current_command} #[fg=#252434,bg=#bac2de] #I #[fg=#bac2de,bg=default]"
set -g window-status-separator ""
set -g window-status-style "bg=default,fg=#252434"

set -g extended-keys on
set -g extended-keys-format csi-u

run '~/.config/tmux/plugins/tpm/tpm'
