#!/bin/sh

riverctl map normal Super Return spawn "st"

riverctl map normal Super+Shift Space spawn "tofi-drun --drun-launch=true"
riverctl map normal Super+Shift B spawn "killall waybar && waybar -c ~/.config/waybar/config.jsonc"

riverctl map normal None PRINT spawn "grim ~/Pictures/screenshots/$(date +%Y-%m-%d-%H-%M-%S).png"
riverctl map normal Super PRINT spawn "grim - | wl-copy -t image/png"
riverctl map normal Super+Shift PRINT spawn "slurp | grim -g - - | wl-copy -t image/png"

riverctl map normal Super+Shift D spawn "putty -load VPS\ Dou"

riverctl map normal Super Q close
riverctl map normal Super+Shift E exit
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous
riverctl map normal Super+Shift Return zoom

riverctl map normal Super Right spawn "river-shifttags --shifts 1"
riverctl map normal Super Left spawn "river-shifttags --shifts -1"

riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9); do
  tags=$((1 << ($i - 1)))

  riverctl map normal Super $i set-focused-tags $tags
  riverctl map normal Super+Shift $i set-view-tags $tags
  riverctl map normal Super+Control $i toggle-focused-tags $tags
  riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))

riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags
riverctl map normal Super V toggle-float
riverctl map normal Super F toggle-fullscreen
# riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
# riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
# riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
# riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

riverctl declare-mode passthrough

riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

for mode in normal locked; do
  riverctl map $mode None XF86Eject spawn 'eject -T'
  riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
  riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
  riverctl map $mode None XF86AudioMute spawn 'pamixer --toggle-mute'
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext spawn 'playerctl next'
  riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
  riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

riverctl background-color 0x000000
riverctl border-color-focused 0x383636
riverctl border-color-unfocused 0x2a2929
riverctl border-width 1

riverctl set-repeat 50 300

riverctl spawn "riveroverflow"

riverctl default-layout riveroverflow

riverctl send-layout-cmd riveroverflow "main_count 2"
riverctl send-layout-cmd riveroverflow "main_ratio 0.5"
riverctl send-layout-cmd riveroverflow "view_padding 0"
riverctl send-layout-cmd riveroverflow "outer_padding 1"
riverctl send-layout-cmd riveroverflow "view_per_page 4"

riverctl map normal Super+Control J send-layout-cmd riveroverflow page_down
riverctl map normal Super+Control K send-layout-cmd riveroverflow page_up

riverctl keyboard-layout -options 'grp:alt_space_toggle' us,latam

riverctl rule-add -app-id 'librewolf' tags $((1 << 2))
riverctl rule-add -app-id 'discord' tags $((1 << 3))
riverctl rule-add -app-id 'Spotify' tags $((1 << 4))

riverctl rule-add -app-id 'PasswordSafe (linux)' float
riverctl rule-add -app-id 'Thunar' float
riverctl rule-add -app-id 'thunar' float
riverctl rule-add -app-id 'zoom' float
riverctl rule-add -app-id 'Emulator' float
riverctl rule-add -app-id 'virt-manager' float
riverctl rule-add -app-id 'org.pulseaudio.pavucontrol' float
riverctl rule-add -app-id 'io.github.Qalculate.qalculate-qt' float
riverctl rule-add -app-id 'com.github.jmoerman.go-for-it' float
riverctl rule-add -app-id 'localsend' float

riverctl rule-add -title 'Picture-in-Picture' float

riverctl xcursor-theme McMojave-cursors
riverctl spawn "gsettings set org.gnome.desktop.interface cursor-theme McMojave-cursors"

riverctl spawn "pipewire"
riverctl spawn "swaync"
riverctl spawn "swww-daemon --no-cache --format xrgb"
riverctl spawn "$HOME/.config/river/scripts/wallpaper.sh"
riverctl spawn "waybar"
riverctl spawn "/usr/libexec/polkit-kde-authentication-agent-1"
riverctl spawn "dbus-update-activation-environment DISPLAY I3SOCK SWAYSOCK WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=$nameofcompositor"
