;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

# Import modules and current theme
include-file = ~/.config/polybar/modules.ini
include-file = ~/.config/polybar/themes/dark.ini

[bar/main]
# Geometry
# bottom = true
width = 100%
height = 34
# offset-x = 1%
# offset-y = 1%
# radius = 12
# padding-right = 10
# radius-bottom-left = 12
# radius-bottom-right = 12

# Styling
background = ${colors.background}
foreground = ${colors.foreground}
font-0 = Noto Sans:style=Bold:size=9.5;4
font-1 = FiraCode Nerd Font:style=Regular:size=12;3
cursor-click = pointer
cursor-scroll = ns-resize
line-size = 8
padding = 4

# Modules
modules-left = logo SEPARATOR workspaces title
modules-center = date SEPARATOR temp SEPARATOR
modules-right = cpu SEPARATOR memory SEPARATOR disk SEPARATOR output volume keyboard clipboard notifications network power

# Other
override-redirect = true
wm-restack = bspwm

[settings]
pseudo-transparency = true
