# Module decorators

[module/SEPARATOR]
type = custom/text
label = " "
label-padding-left = 3
label-padding-right = 3
label-foreground = ${colors.raised}

# Polybar modules

[module/logo]
type = custom/text
label = 
label-padding-left = 2
label-foreground = #70e000
click-left = rofi -config ~/.config/rofi/rofi.rasi -show drun
click-right = rofi -config ~/.config/rofi/rofi.rasi -show window

[module/workspaces]
type = internal/bspwm
pin-workspaces = true
reverse-scroll = false
wrapping-scroll = false
label-mode-padding = 1
label-mode-foreground = ${colors.urgent}
label-focused = %index%
label-focused-padding = 1
label-focused-foreground = ${colors.foreground}
label-dimmed = %index%
label-dimmed-padding = 1
label-dimmed-foreground = ${colors.empty}
label-occupied = %index%
label-occupied-padding = 1
label-occupied-foreground = ${colors.foreground-alt}
label-urgent = %index%
label-urgent-padding = 1
label-urgent-foreground = ${colors.urgent}
label-empty = ""
label-mode = 󰲏

[module/title]
type = internal/xwindow
label = 󰁤   %class%
label-empty =     bspwm
label-padding-left = 4
label-empty-padding-left = 4

[module/date]
format = <label>  󰃭
type = custom/script
interval = 1
exec = echo $(date +"%Y-%m-%d %H:%M")
click-left = ~/.config/polybar/scripts/calendar.sh
scroll-up = ~/.config/polybar/scripts/calendar.sh next
scroll-down = ~/.config/polybar/scripts/calendar.sh prev

[module/temp]
type = internal/temperature
interval = 1.0
thermal-zone = 0
zone-type = acpitz
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input
base-temperature = 20
warn-temperature = 70
format = <label> 
format-warn = <label-warn>
label = %temperature-c%  
label-warn = %temperature-c%  
label-warn-foreground = #f72585

[module/cpu]
type = internal/cpu
format = <label>  
label-padding-left = 1

[module/memory]
type = internal/memory
format = <label>  
label-padding-left = 1

[module/disk]
type = internal/fs
format-mounted = <label-mounted> 
label-mounted = %percentage_used%%
label-mounted-padding-left = 1
label-warn = %percentage_used%%
warn-percentage = 75

[module/output]
type = custom/script
label-padding-right = 2
interval = 0.5
exec = ~/.config/polybar/scripts/audio_icon.sh
click-left = ~/.config/polybar/scripts/audio_switcher.sh

[module/volume]
type = internal/pulseaudio
use-ui-max = false
format-volume = <bar-volume>
format-volume-padding = 2
format-muted = <bar-volume>
format-muted-padding = 2
bar-volume-width = 10
bar-volume-fill = 󱪼
bar-volume-empty = 󱪼
bar-volume-indicator = ""
bar-volume-gradient = false
bar-volume-foreground-0 = ${colors.foreground}
bar-volume-foreground-1 = ${colors.foreground}
bar-volume-foreground-2 = ${colors.foreground}
bar-volume-foreground-3 = ${colors.urgent}
bar-volume-empty-foreground = ${colors.empty}

[module/keyboard]
type = internal/xkeyboard
format = <label-layout>
format-padding = 2
label-layout = %icon%
layout-icon-0 = us;󰌌
layout-icon-1 = latam;%{F#ff7432}󰌌


[module/clipboard]
type = custom/text
label = 󰅇
label-padding = 2
click-left = CM_LAUNCHER=rofi clipmenu -config ~/.config/rofi/clipboard.rasi -i

[module/xbacklight]
type = internal/xbacklight
label = 󰃝
label-padding = 2
click-left = dunstify %percentage%%

[module/notifications]
type = custom/script
label-padding = 2
interval = 0.5
exec = [ "$(dunstctl is-paused)" = "true" ] && echo "%{F#ff7043}󱏫%{F-}" || echo 󰂚
click-left = dunstctl set-paused toggle

[module/network]
type = internal/network
interval = 5
interface-type = wireless
format-connected = <label-connected>
label-connected = 󰖩
label-connected-padding = 2
format-disconnected = <label-disconnected>
label-disconnected = 󰖪
label-disconnected-padding = 2
label-disconnected-foreground = ${colors.urgent}
format-packetloss = <label-packetloss>
label-packetloss = 󱚵
label-packetloss-padding = 2 

[module/power]
type = custom/text
label = ⏼
label-padding-left = 2
label-padding-right = 2
label-foreground = ${colors.urgent}
click-left = ~/.config/polybar/scripts/power.sh
